name: Multiple jobs

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install cowsay program
        run: sudo apt-get install cowsay -y
      - name: execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a Dragon... .RAWr" > dragon.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt

  test_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-file
      - name: test file Exists
        run: grep -i "dragon" dragon.txt