name: First Workflow

on:
  push:
    branches:
      - main  

jobs:
  first_job:
    runs-on: self-hosted
    steps:
      - name: list files
        run: echo "CICD"
  second_job:
    needs: first_job
    runs-on: self-hosted
    steps:
      - name: list files
        run: echo "CICD2"

